/* Generated by lang. Trusted C/Clang lowering; u64 arithmetic is modular. */
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
bool lang_fn_conjunction(bool lang_a0, bool lang_a1, bool lang_a2);
bool lang_fn_disjunction(bool lang_a0, bool lang_a1, bool lang_a2);
bool lang_fn_unguarded(bool lang_a0, bool lang_a1);
bool lang_fn_numeric(uint64_t lang_a0, uint64_t lang_a1, bool lang_a2, bool lang_a3);
bool lang_fn_conjunction(bool lang_a0, bool lang_a1, bool lang_a2) {
    (void)lang_a0;
    (void)lang_a1;
    (void)lang_a2;
    bool lang_t0 = lang_a0;
    if (lang_t0) {
        bool lang_t1 = lang_a0;
        if (lang_t1) {
            lang_t1 = lang_a1;
        }
        bool lang_t2 = lang_t1;
        if (!lang_t2) {
            lang_t2 = lang_a2;
        }
        lang_t0 = lang_t2;
    }
    return lang_t0;
}
bool lang_fn_disjunction(bool lang_a0, bool lang_a1, bool lang_a2) {
    (void)lang_a0;
    (void)lang_a1;
    (void)lang_a2;
    bool lang_t0 = lang_a0;
    if (!lang_t0) {
        bool lang_t1 = lang_a0;
        if (!lang_t1) {
            lang_t1 = lang_a1;
        }
        bool lang_t2 = lang_t1;
        if (lang_t2) {
            lang_t2 = lang_a2;
        }
        lang_t0 = lang_t2;
    }
    return lang_t0;
}
bool lang_fn_unguarded(bool lang_a0, bool lang_a1) {
    (void)lang_a0;
    (void)lang_a1;
    bool lang_t0 = lang_a0;
    if (lang_t0) {
        lang_t0 = lang_a1;
    }
    return lang_t0;
}
bool lang_fn_numeric(uint64_t lang_a0, uint64_t lang_a1, bool lang_a2, bool lang_a3) {
    (void)lang_a2;
    (void)lang_a3;
    (void)lang_a1;
    (void)lang_a0;
    bool lang_t0 = (lang_a0 < lang_a1);
    if (lang_t0) {
        bool lang_t1 = (lang_a0 < lang_a1);
        if (lang_t1) {
            lang_t1 = lang_a2;
        }
        bool lang_t2 = lang_t1;
        if (!lang_t2) {
            lang_t2 = lang_a3;
        }
        lang_t0 = lang_t2;
    }
    return lang_t0;
}
