[package]
name = "ink-lowering-gpu"
version = "0.1.0"
edition = "2021"
publish = false
[dependencies]
ink-core = { git = "https://github.com/siliconjungle/ink-lang", rev = "f7ba1006f1c4fb11b61774b47180eddbaa68f2f7" }
ink-lowering-c = { git = "https://github.com/siliconjungle/ink-lowering-c", rev = "d13ea2a03f5eebad9271f123628214e751ca8c86" }
serde_json = "1"
sha2 = "0.10"
