/* Generated by lang. Trusted C/Clang lowering; u64 arithmetic is modular. */
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
/* Base allocation mechanism for literal collection operations; no fusion law. */
#define LANG_UNUSED __attribute__((unused))
#if defined(__wasm__)
extern unsigned char __heap_base;
typedef struct lang_block { size_t previous_top; struct lang_block *previous; uint64_t released; } lang_block;
typedef struct { size_t top; lang_block *last; } lang_frame;
static size_t lang_top;
static lang_block *lang_last;
static LANG_UNUSED void lang_fail(void) { __builtin_trap(); }
static LANG_UNUSED lang_frame lang_enter(void) {
    lang_frame frame={lang_top,lang_last};
    if (lang_top<(size_t)&__heap_base) lang_top=(size_t)&__heap_base;
    return frame;
}
static LANG_UNUSED void lang_input(const uint64_t *data,size_t length) {
    if (length>SIZE_MAX/8 || (size_t)data>SIZE_MAX-length*8) lang_fail();
    size_t end=(size_t)data+length*8;if(end>lang_top) lang_top=end;
}
static LANG_UNUSED void lang_exit(lang_frame frame) { lang_top=frame.top;lang_last=frame.last; }
static LANG_UNUSED uint64_t *lang_allocate(size_t count) {
    if(!count)count=1;
    if(count>SIZE_MAX/8 || lang_top>SIZE_MAX-7) lang_fail();
    size_t start=(lang_top+7)&~(size_t)7;
    if(start>SIZE_MAX-sizeof(lang_block) || count*8>SIZE_MAX-start-sizeof(lang_block))lang_fail();
    size_t end=start+sizeof(lang_block)+count*8;
    size_t needed=(size_t)(((uint64_t)end+65535)/65536),pages=__builtin_wasm_memory_size(0);
    if(needed>pages && __builtin_wasm_memory_grow(0,needed-pages)==(size_t)-1)lang_fail();
    lang_block *block=(lang_block*)start;block->previous_top=lang_top;block->previous=lang_last;block->released=0;
    lang_last=block;lang_top=end;return (uint64_t*)(block+1);
}
static LANG_UNUSED void lang_release(uint64_t *data) {
    ((lang_block*)data-1)->released=1;
    while(lang_last && lang_last->released) {size_t top=lang_last->previous_top;lang_block *previous=lang_last->previous;lang_top=top;lang_last=previous;}
}
#else
#include <stdlib.h>
typedef unsigned char lang_frame;
static LANG_UNUSED lang_frame lang_enter(void) {return 0;}
static LANG_UNUSED void lang_input(const uint64_t *data,size_t length) {(void)data;(void)length;}
static LANG_UNUSED void lang_exit(lang_frame frame) {(void)frame;}
static LANG_UNUSED uint64_t *lang_allocate(size_t count) {
    if(count>SIZE_MAX/sizeof(uint64_t))abort();
    uint64_t *data=malloc((count?count:1)*sizeof(uint64_t));if(!data)abort();return data;
}
static LANG_UNUSED void lang_release(uint64_t *data) {free(data);}
#endif
uint64_t lang_fn_project(uint64_t lang_a0, uint64_t lang_a1, uint64_t lang_a2);
bool lang_fn_under(uint64_t lang_a0, uint64_t lang_a1);
uint64_t lang_fn_mapped_filter_sum(const uint64_t *lang_a0_data, size_t lang_a0_len, uint64_t lang_a1, uint64_t lang_a2, uint64_t lang_a3);
uint64_t lang_fn_filter_map_sum(const uint64_t *lang_a0_data, size_t lang_a0_len, uint64_t lang_a1, uint64_t lang_a2, uint64_t lang_a3);
uint64_t lang_fn_mapped_filter_count(const uint64_t *lang_a0_data, size_t lang_a0_len, uint64_t lang_a1, uint64_t lang_a2, uint64_t lang_a3);
uint64_t lang_fn_constant_filter_sum(const uint64_t *lang_a0_data, size_t lang_a0_len, uint64_t lang_a1, uint64_t lang_a2, uint64_t lang_a3);
uint64_t lang_fn_project(uint64_t lang_a0, uint64_t lang_a1, uint64_t lang_a2) {
    lang_frame lang_saved_frame=lang_enter();
    (void)lang_a2;
    (void)lang_a1;
    (void)lang_a0;
    uint64_t lang_t0=((lang_a0 * lang_a1) + lang_a2);
    lang_exit(lang_saved_frame);
    return lang_t0;
}
bool lang_fn_under(uint64_t lang_a0, uint64_t lang_a1) {
    lang_frame lang_saved_frame=lang_enter();
    (void)lang_a1;
    (void)lang_a0;
    bool lang_t0=(lang_a0 < lang_a1);
    lang_exit(lang_saved_frame);
    return lang_t0;
}
uint64_t lang_fn_mapped_filter_sum(const uint64_t *lang_a0_data, size_t lang_a0_len, uint64_t lang_a1, uint64_t lang_a2, uint64_t lang_a3) {
    lang_frame lang_saved_frame=lang_enter();
    lang_input(lang_a0_data,lang_a0_len);
    (void)lang_a2;
    (void)lang_a3;
    (void)lang_a1;
    (void)lang_a0_data;
    (void)lang_a0_len;
    uint64_t lang_t0=UINT64_C(0);
    for (size_t lang_t1=lang_a0_len; lang_t1>0; --lang_t1) {
        uint64_t lang_t2=lang_a0_data[lang_t1-1];
        (void)lang_t2;
        uint64_t lang_t3=lang_fn_project(lang_t2, lang_a1, lang_a2);
        bool lang_t4=lang_fn_under(lang_t3, lang_a3);
        uint64_t lang_t5;
        if (lang_t4) {
            uint64_t lang_t6=lang_fn_project(lang_t2, lang_a1, lang_a2);
            lang_t5=(lang_t6 + lang_t0);
        } else {
            lang_t5=lang_t0;
        }
        lang_t0=lang_t5;
    }
    uint64_t lang_t7=lang_t0;
    lang_exit(lang_saved_frame);
    return lang_t7;
}
uint64_t lang_fn_filter_map_sum(const uint64_t *lang_a0_data, size_t lang_a0_len, uint64_t lang_a1, uint64_t lang_a2, uint64_t lang_a3) {
    lang_frame lang_saved_frame=lang_enter();
    lang_input(lang_a0_data,lang_a0_len);
    (void)lang_a2;
    (void)lang_a3;
    (void)lang_a1;
    (void)lang_a0_data;
    (void)lang_a0_len;
    uint64_t *lang_t0 = lang_allocate(lang_a0_len);
    size_t lang_t1 = 0;
    for (size_t lang_t2=0; lang_t2<lang_a0_len; ++lang_t2) {
        uint64_t lang_t3=lang_a0_data[lang_t2];
        (void)lang_t3;
        bool lang_t4=lang_fn_under(lang_t3, lang_a3);
        if (lang_t4) lang_t0[lang_t1++] = lang_t3;
    }
    uint64_t *lang_t5 = lang_allocate(lang_t1);
    size_t lang_t6 = 0;
    for (size_t lang_t7=0; lang_t7<lang_t1; ++lang_t7) {
        uint64_t lang_t8=lang_t0[lang_t7];
        (void)lang_t8;
        uint64_t lang_t9=lang_fn_project(lang_t8, lang_a1, lang_a2);
        lang_t5[lang_t6++] = lang_t9;
    }
    lang_release(lang_t0);
    uint64_t lang_t10=0;
    for (size_t lang_t11=lang_t6; lang_t11>0; --lang_t11) {
        lang_t10 += lang_t5[lang_t11-1];
    }
    lang_release(lang_t5);
    uint64_t lang_t12=lang_t10;
    lang_exit(lang_saved_frame);
    return lang_t12;
}
uint64_t lang_fn_mapped_filter_count(const uint64_t *lang_a0_data, size_t lang_a0_len, uint64_t lang_a1, uint64_t lang_a2, uint64_t lang_a3) {
    lang_frame lang_saved_frame=lang_enter();
    lang_input(lang_a0_data,lang_a0_len);
    (void)lang_a2;
    (void)lang_a3;
    (void)lang_a1;
    (void)lang_a0_data;
    (void)lang_a0_len;
    uint64_t *lang_t0 = lang_allocate(lang_a0_len);
    size_t lang_t1 = 0;
    for (size_t lang_t2=0; lang_t2<lang_a0_len; ++lang_t2) {
        uint64_t lang_t3=lang_a0_data[lang_t2];
        (void)lang_t3;
        uint64_t lang_t4=lang_fn_project(lang_t3, lang_a1, lang_a2);
        lang_t0[lang_t1++] = lang_t4;
    }
    uint64_t *lang_t5 = lang_allocate(lang_t1);
    size_t lang_t6 = 0;
    for (size_t lang_t7=0; lang_t7<lang_t1; ++lang_t7) {
        uint64_t lang_t8=lang_t0[lang_t7];
        (void)lang_t8;
        bool lang_t9=lang_fn_under(lang_t8, lang_a3);
        if (lang_t9) lang_t5[lang_t6++] = lang_t8;
    }
    lang_release(lang_t0);
    uint64_t lang_t10=(uint64_t)lang_t6;
    lang_release(lang_t5);
    uint64_t lang_t11=lang_t10;
    lang_exit(lang_saved_frame);
    return lang_t11;
}
uint64_t lang_fn_constant_filter_sum(const uint64_t *lang_a0_data, size_t lang_a0_len, uint64_t lang_a1, uint64_t lang_a2, uint64_t lang_a3) {
    lang_frame lang_saved_frame=lang_enter();
    lang_input(lang_a0_data,lang_a0_len);
    (void)lang_a2;
    (void)lang_a3;
    (void)lang_a1;
    (void)lang_a0_data;
    (void)lang_a0_len;
    uint64_t *lang_t0 = lang_allocate(lang_a0_len);
    size_t lang_t1 = 0;
    for (size_t lang_t2=0; lang_t2<lang_a0_len; ++lang_t2) {
        uint64_t lang_t3=lang_a0_data[lang_t2];
        (void)lang_t3;
        lang_t0[lang_t1++] = lang_a2;
    }
    uint64_t *lang_t4 = lang_allocate(lang_t1);
    size_t lang_t5 = 0;
    for (size_t lang_t6=0; lang_t6<lang_t1; ++lang_t6) {
        uint64_t lang_t7=lang_t0[lang_t6];
        (void)lang_t7;
        bool lang_t8=lang_fn_under(lang_t7, lang_a3);
        if (lang_t8) lang_t4[lang_t5++] = lang_t7;
    }
    lang_release(lang_t0);
    uint64_t lang_t9=0;
    for (size_t lang_t10=lang_t5; lang_t10>0; --lang_t10) {
        lang_t9 += lang_t4[lang_t10-1];
    }
    lang_release(lang_t4);
    uint64_t lang_t11=lang_t9;
    lang_exit(lang_saved_frame);
    return lang_t11;
}
