/* Generated by lang. Trusted C/Clang lowering; u64 arithmetic is modular. */
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
bool lang_fn_decision(uint64_t lang_a0, uint64_t lang_a1, bool lang_a2);
bool lang_fn_decision(uint64_t lang_a0, uint64_t lang_a1, bool lang_a2) {
    (void)lang_a2;
    (void)lang_a1;
    (void)lang_a0;
    return (lang_a0 < lang_a1);
}
