/* Generated by lang. Trusted C/Clang lowering; u64 arithmetic is modular. */
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
bool lang_fn_decision(bool lang_a0, bool lang_a1);
bool lang_fn_repeated(uint64_t lang_a0, uint64_t lang_a1);
bool lang_fn_decision(bool lang_a0, bool lang_a1) {
    (void)lang_a0;
    (void)lang_a1;
    return lang_a0;
}
bool lang_fn_repeated(uint64_t lang_a0, uint64_t lang_a1) {
    (void)lang_a1;
    (void)lang_a0;
    bool lang_t0 = (lang_a0 < lang_a1);
    if (lang_t0) {
        lang_t0 = (lang_a0 < lang_a1);
    }
    return lang_t0;
}
